### ISSUE TITLE
CIFAR10 Dataset / Download script upload? 

### ISSUE THREAD

**Issue by wady101** [XinDongol/BENN-PyTorch#1]
Hi authors, 
I am trying to train the CIFAR10 dataset using boostA-sequential-AB BNN model from scratch:

_Command used_
`python main_boostA_AB_seq.py --epochs 10 --data ../../SB/boosting/data/`

_Error message_
```
Traceback (most recent call last):
  File "main_boostA_AB_seq.py", line 353, in <module>
    train(epoch)
  File "main_boostA_AB_seq.py", line 106, in train
    output = model(data)
  File "/home/wadhwae/miniconda3/envs/benn/lib/python3.7/site-packages/torch/nn/modules
/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wadhwae/miniconda3/envs/benn/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/wadhwae/miniconda3/envs/benn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wadhwae/workspace/Training/BENN-PyTorch/cifar/AB/boosting/../../models/nin.py", line 
225, in forward
    x = self.xnor(x)
  File "/home/wadhwae/miniconda3/envs/benn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wadhwae/miniconda3/envs/benn/lib/python3.7/site-packages/torch/nn/modules
/container.py", line 92, in forward
    input = module(input)
  File "/home/wadhwae/miniconda3/envs/benn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wadhwae/workspace/Training/BENN-PyTorch/cifar/AB/boosting/../../models/nin.py", line 44, in forward
    x = self.bn(x)
  File "/home/wadhwae/miniconda3/envs/benn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wadhwae/miniconda3/envs/benn/lib/python3.7/site-packages/torch/nn/modules/batchnorm.py", line 59, in forward
    self._check_input_dim(input)
  File "/home/wadhwae/miniconda3/envs/benn/lib/python3.7/site-packages/torch/nn/modules/batchnorm.py", line 244, in _check_input_dim
    .format(input.dim()))
ValueError: expected 4D input (got 2D input)
```

Even if I retrain the model using  `python main_boostA_AB_seq.py --epochs 0 --retrain_epochs 0 --data ../../SB/boosting/data/`, (with all the 31 epochs tar files in models_boostA_AB_seq/ ) I am still getting the above error. 

_Error Message_

```
==> Load pretrained model from ...
boosting 0
2020-01-04 15:51:51.598063 Start boosting iter: 0
===> Start retraining ...
Traceback (most recent call last):
  File "main_boostA_AB_seq.py", line 368, in <module>
    sample_weights_new, alpha_m = sample_models(boosting_iters=i, sample_weights=sample_weights_new, retrain_epoch=args.retrain_epochs)
  File "main_boostA_AB_seq.py", line 294, in sample_models
    batch_softmax_output = get_error_output(data, target, batch_sample_weights)
  File "main_boostA_AB_seq.py", line 263, in get_error_output
    output = model(data)
  File "/home/wadhwae/miniconda3/envs/benn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wadhwae/miniconda3/envs/benn/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/wadhwae/miniconda3/envs/benn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wadhwae/workspace/Training/BENN-PyTorch/cifar/AB/boosting/../../models/nin.py", line 225, in forward
    x = self.xnor(x)
  File "/home/wadhwae/miniconda3/envs/benn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wadhwae/miniconda3/envs/benn/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/wadhwae/miniconda3/envs/benn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wadhwae/workspace/Training/BENN-PyTorch/cifar/AB/boosting/../../models/nin.py", line 44, in forward
    x = self.bn(x)
  File "/home/wadhwae/miniconda3/envs/benn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wadhwae/miniconda3/envs/benn/lib/python3.7/site-packages/torch/nn/modules/batchnorm.py", line 59, in forward
    self._check_input_dim(input)
  File "/home/wadhwae/miniconda3/envs/benn/lib/python3.7/site-packages/torch/nn/modules/batchnorm.py", line 244, in _check_input_dim
    .format(input.dim()))
ValueError: expected 4D input (got 2D input)
```
I only can suspect here that I have wrongly saved / pre-processed the CIFAR10 dataset (I have saved the dataset as train_data, train_labels, test_data and test_labels in numpy files and read from it using the data.py file provided, no pre-processing done).

**Comment by wady101** [comment]
Issue resolved. Refer to https://github.com/jiecaoyu/XNOR-Net-PyTorch/issues/54

**Comment by zwd2016** [comment]
> Issue resolved. Refer to [jiecaoyu/XNOR-Net-PyTorch#54](https://github.com/jiecaoyu/XNOR-Net-PyTorch/issues/54)
Dear wady101 @wady101,
My PyTorch version is 0.4.1 and the python version is 3.6.9.
I am executing the same command as follows:
`python main_boostA_AB_seq.py --epochs 10 --data ../../SB/boosting/data/`
I found that the `index` (i.e., tensor)  in `data_new.py` needs to be set to LongTensor, and I continued to modify it to `index.long()`. After running again, I got this strange error:
`RuntimeError: Expected 4-dimensional input for 4-dimensional weight [192, 3, 5, 5], but got input size [128, 1, 3, 32, 32] instead`
I retrain the model using `python main_boostA_AB_seq.py --epochs 0 --retrain_epochs 100 --data ../../SB/boosting/data/`. I got this error after 5 normal epochs:
`RuntimeError: CUDA out of memory.` 
However, look at the GPU usage at 3.8 / 8.0 GB
Can you successfully run this code now? If you have a good solution, please let me know.
Thank you very much!
